FROM tensorflow/tensorflow:latest-gpu

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y python3-opencv

RUN python3 -m pip install --upgrade pip && \
    pip3 install \
    gym[atari,accept-rom-license] \
    opencv-python \
    pygame \
    tensorflow-probability \
    scipy
