FROM tensorflow/tensorflow:latest-gpu

RUN apt-get -y update && \
    apt-get -y upgrade

RUN python3 -m pip install --upgrade pip && \
    pip3 install \
    gym[atari,accept-rom-license] \
    opencv_python \
    pygame \
    tensorflow-probability
